server:
  port: 8080
  error:
    include-stacktrace: always

spring:
  application:
    name: ecom
  profiles:
    active: default
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
  data:
    cassandra:
      schema-action: create-if-not-exists

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true