name: Publish container images

on:
  workflow_dispatch:

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build UI
        run: npm --prefix ui install && npm --prefix ui run build
      - name: Build with Maven and publish image
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn spring-boot:build-image -DskipTests=true -Dspring-boot.boot-image.publish=true --file backend/pom.xml
